auto: true

markdown: kramdown
input: GFM
highlighter: rouge

gems: [jekyll-paginate]
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

title: olamha's blog
url: 
feed: /atom.xml
author_info: 
